### ISSUE TITLE
大佬，代码什么时候开源呢？想试试

### ISSUE THREAD

**Issue by Wulingtian** [zhangchbin/OnlineLabelSmoothing#2]
类别不均衡的数据，或许有奇效

**Comment by zhangchbin** [comment]
目前paper还在审稿中，所以开源代码估计还会等一段时间，不过您提到的类别不均衡的数据，我们之前没有尝试过，是一个值得研究的地方。感谢您的关注和建议。

**Comment by Wulingtian** [comment]
> 目前paper还在审稿中，所以开源代码估计还会等一段时间，不过您提到的类别不均衡的数据，我们之前没有尝试过，是一个值得研究的地方。感谢您的关注和建议。

大佬，开源的时候记得通知我一声！

**Comment by zhangchbin** [comment]
> > 目前paper还在审稿中，所以开源代码估计还会等一段时间，不过您提到的类别不均衡的数据，我们之前没有尝试过，是一个值得研究的地方。感谢您的关注和建议。
> 
> 大佬，开源的时候记得通知我一声！

好滴~

**Comment by zhangchbin** [comment]
Hi, @Wulingtian 
There is a re-implementation updated in the README.
