### ISSUE TITLE
论文中BYOT的实现问题

### ISSUE THREAD

**Issue by beiliu604** [zhangchbin/OnlineLabelSmoothing#3]
作者您好，

我看到这篇论文中使用了BYOT，我读了BYOT的原文，但是没有找到官方开源的代码，只在github看到一个实现:
[https://github.com/luanyunteng/pytorch-be-your-own-teacher](https://github.com/luanyunteng/pytorch-be-your-own-teacher)。

但是这个实现和原文中的结果差别挺大，您论文中BYOT用ResNet50在CIFAR-100的表现(80.8%)比原作者的还要好一些(80.56%) 

想问一下您是怎么实现BYOT的？谢谢！

**Comment by zhangchbin** [comment]
您好, 由于我们没找到BYOT的官方开源代码, 联系作者却发现邮箱地址已经不存在,所以我们就使用了这个github上的复现,我们也注意到了这个实现和原文中结果的差别,我们也尝试在这个复现的代码上修改一些地方,但都得到了相似的结果,所以最后我们就直接使用了这个非官方实现的代码.

**Comment by beiliu604** [comment]
好的，感谢回复！

**Comment by zhangchbin** [comment]
Hi, @beiliu253 
There is a re-implement updated in the README.

**Comment by beiliu604** [comment]
好的，感谢，我参考一下 @zhangchbin
