### ISSUE TITLE
相似工作：Label Embedding Network

### ISSUE THREAD

**Issue by hemingkx** [zhangchbin/OnlineLabelSmoothing#4]
您好！在读您的论文时，感觉和北大语言所孙栩老师2017年的工作非常像，附上文章名称和链接，供您参考。

论文名称和链接：
Label Embedding Network: Learning Label Representation for Soft Training of Deep Networks
http://arxiv.org/abs/1710.10393

**Comment by zhangchbin** [comment]
Hi, @hemingkx 
我阅读了孙老师的论文，Label Embedding Network和我们的motivation是相似的，但是方法有很大不同。

**Comment by hemingkx** [comment]
嗯嗯， @zhangchbin ，如果论文中能有和孙老师模型效果的对比就更好了，只是一个小小的建议😊～

**Comment by zhangchbin** [comment]
hi, @hemingkx ,
感谢您的建议，等后面有时间，我会尝试在imageNet上和Label Embedding Network 对比。

**Comment by hemingkx** [comment]
好的～
