### ISSUE TITLE
solver.py中清空cur_loss的疑问

### ISSUE THREAD

**Issue by jie74** [zhangchbin/OnlineLabelSmoothing#5]
您好，请问在solver.py中193行处，为什么要在这个时机要清空cur_loss，请指教
 if (i+1) % (len(dataset)//2//self.args.batch_size) == 0:
    print('%s [epoch %d/%d, iter %d/%d] lr = %f cur_loss = %f avg_loss = %f' % (time_now, epoch, self.args.epochs, i, len(dataloader), optimizer.param_groups[0]['lr'], cur_loss/100, loss_recoder.avg))
    cur_loss = 0

**Comment by zhangchbin** [comment]
您好，这里的```cur_loss```是为了统计一段时间内的平均损失的，这个只是用来打印损失的。

**Comment by jie74** [comment]
那我可以理解为只是在一半epoch时打印一下，看下当前损失吗，甚至乎删掉也无伤大雅？

**Comment by zhangchbin** [comment]
是的，删掉也没关系的，只是用来看下当前损失是多少

**Comment by jie74** [comment]
谢谢您的回复
